networks:
  cssninja-services:
    external: true

services:
  kinesis-demo:
    image: digisquad/cssninja.kinesis-demo:latest
    networks:
      - cssninja-services
    restart: "unless-stopped"
    labels:
      traefik.enable: true
      traefik.docker.network: "cssninja-services"
      traefik.http.routers.kinesis-demo.entrypoints: "http"
      traefik.http.routers.kinesis-demo.rule: "Host(`kinesis.${HOST:-127.0.0.1.nip.io}`)"
      traefik.http.routers.kinesis-demo.middlewares: "https-redirect@file"
      traefik.http.services.kinesis-demo-https.loadbalancer.server.port: 8080
      traefik.http.routers.kinesis-demo-https.rule: "Host(`kinesis.${HOST:-127.0.0.1.nip.io}`)"
      traefik.http.routers.kinesis-demo-https.tls: true
      traefik.http.routers.kinesis-demo-https.entrypoints: "https"
      traefik.http.routers.kinesis-demo-https.tls.certresolver: "http"
